### ISSUE TITLE
LCP Integration

### ISSUE THREAD

**Issue by leomoty** [edrlab/r2-streamer-js#31]
Hello @danielweck, I am a bit confused regarding how this can be integrated with `LCP Server` stack.

I noticed that encryption.md talks about `LSD Server` as being interesting to have, thus it is not supported, right?

That being the case, there is a demo for a protected epub with `LCP passphrase` "dan", does that mean that I would need to serve one protected epub per user with the `LCP passphrase` built-in?

If so, how could I achieve that for testing? I tried serving the `encrypted` folder from `LCP Server`, but from my understanding there is no passphrase associated with that epub at all.

**Comment by danielweck** [comment]
Firstly, LSD support is implemented in `readium-desktop` and `r2-testapp-js` with varying degrees of UX completeness (the most polished user experience is of course provided by the "Readium Desktop" app). The `r2-streamer-js` "streamer" component itself only supports low-level resource decryption / de-obfuscation (no sophisticated LCP DRM features). The streamer LCP functionality is really meant to be integrated via some additional application logic (see `readium-desktop` and `r2-testapp-js`), so that the full LCP+LSD experience is delivered as part of a "packaged" app (server backend + client frontend). You can of course deploy the streamer module on its own, "simulate" passing the user passphrase via the URL, and obtain decrypted HTTP responses (see https://github.com/edrlab/r2-streamer-js/blob/develop/docs/encryption.md ). However this is not a secure and scalable solution, it is just a demo (not recommended practice).

Secondly, the Go LCP server is designed to process EPUBs with encrypted resources inside (using the "content key"), but more importantly to generate protected publications with LCP licenses injected as `META-INF/license.lcpl` (which provides the "user key"-encrypted "content key").

**Comment by danielweck** [comment]
Could you please remind us what you are trying to use `r2-streamer-js` for? Are you building an app, a web service, etc.?

**Comment by leomoty** [comment]
Sorry for all these questions, @danielweck. We are building both a web platform and mobile solution.  It is pretty clear by now, that I cant realistically expect the full LSD+LSD experience from the web. So i'll see what are our options. Thanks for all your responses.

**Comment by danielweck** [comment]
No problems :)
Yes, on the web, there are other conventions to "protect" resources. DRM is not directly applicable.
