### ISSUE TITLE
Fetching Media Overlay Spine Item resource fails with CORS

### ISSUE THREAD

**Issue by barbender** [edrlab/r2-streamer-js#5]
This happens in  R1 reader with Node JS R2 streamer testing MO functionality.
R1 reader pointing to R2 Web Pub manifest served by Node JS R2 streamer:
http://localhost:8080/dev/index_RequireJS_no-optimize_LITE.html?epub=http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/manifest.json

When MO data for Spine Item is accessed, fetch is failing with CORS:

Fetch API cannot load
http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp022.xhtml. Redirect
from
'http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp022.xhtml'
to
'http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay/?resource=OEBPS%2FText%2Fp022.xhtml'
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is
present on the requested resource. Origin 'http://localhost:8080' is therefore
not allowed access. If an opaque response serves your needs, set the request's
mode to 'no-cors' to fetch the resource with CORS disabled.

Indeed Network tab shows redirection from:

Request URL:http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp003.xhtml

to:

Location:/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay/?resource=OEBPS%2FText%2Fp003.xhtml

- R2 Node JS Streamer log shows:

r2:server:main REDIRECT: /pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp010.xhtml ==> /pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay/?resource=OEBPS%2FText%2Fp010.xhtml +37s
::1 - - [10/Jun/2017:00:52:56 +0000] "GET /pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp010.xhtml HTTP/1.1" 301 161 "http://localhost:8080/dev/index_RequireJS_no-optimize_LITE.html?epub=http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/manifest.json" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

Here is the environment:
- R1 reader
cd ~/ep/readium/readium-js-viewer
npm run http

- R2 streamer
cd ~/r2-streamer-js
yarn run server-debug .

Note, that there is no problem accessing this URL directly:
http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp003.xhtml

**Comment by danielweck** [comment]
Assuming you are testing with this EPUB3 Media Overlays (Tales From
Shakespeare):
https://www.readbeyond.it/ebooks/08722688.html
...then the direct Readium2 NodeJS streamer link is:
https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI=/manifest.json/show/all
...and the Readium1/2 cloud reader link is (no Media Overlays support yet,
so audio controls are not displayed):
http://readium-2.surge.sh/?epub=https%3A%2F%2Freadium2.herokuapp.com%2Fpub%2FaHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D%2Fmanifest.json

More to the point, this is chapter one's SMIL:
https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D/media-overlay/?show=OEBPS%2FText%2Fp001.xhtml

This is the output from cURL (with -I option to show the HTTP headers):

curl -I
https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D/media-overlay/?resource=OEBPS%2FText%2Fp001.xhtml

HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Ranges,
Link, Transfer-Encoding
Content-Type: application/vnd.readium.mo+json; charset=utf-8
Etag: 4a0f819a8e40c200f15ad0ffd12afd0c4a91414c48818bed9b6540e96ec61742
Content-Length: 1132
Date: Sun, 11 Jun 2017 22:14:43 GMT
Via: 1.1 vegur

As you can see, there are adequate CORS headers. Perhaps you should run
your tests with 127.0.0.1 instead of localhost? (just a thought, I haven't
tried myself)

Daniel

**Comment by danielweck** [comment]
Assuming you are testing with this EPUB3 Media Overlays (Tales From
Shakespeare):
https://www.readbeyond.it/ebooks/08722688.html
...then the direct Readium2 NodeJS streamer link is:
https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI=/manifest.json/show/all
...and the Readium1/2 cloud reader link is (no Media Overlays support yet,
so audio controls are not displayed):
http://readium-2.surge.sh/?epub=https%3A%2F%2Freadium2.herokuapp.com%2Fpub%2FaHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D%2Fmanifest.json

More to the point, this is chapter one's SMIL:
https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D/media-overlay/?show=OEBPS%2FText%2Fp001.xhtml

This is the output from cURL (with -I option to show the HTTP headers):

curl -I
https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D/media-overlay/?resource=OEBPS%2FText%2Fp001.xhtml

```
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Ranges,
Link, Transfer-Encoding
Content-Type: application/vnd.readium.mo+json; charset=utf-8
Etag: 4a0f819a8e40c200f15ad0ffd12afd0c4a91414c48818bed9b6540e96ec61742
Content-Length: 1132
Date: Sun, 11 Jun 2017 22:14:43 GMT
Via: 1.1 vaguer
```

As you can see, there are adequate CORS headers. Perhaps you should run
your tests with 127.0.0.1 instead of localhost? (just a thought, I haven't
tried myself)

**Comment by barbender** [comment]
Hi Daniel,
Yes, I see your point about the presence of the 'Access-Control-Allow-*'
headers. I also saw them when accessing MO overlay data directly, i.e., from the
Browser, Postman, curl:
http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp001.xhtml

However when doing it from within the code originated from
http://localhost:8080/dev/index_RequireJS_no-optimize_LITE.html the problem
arises. Note, that I also tried to use
http://127.0.0.1:8080/dev/index_RequireJS_no-optimize_LITE.html with the same
result.

Do you know of any other implementations that use Node JS R2 streamer cross
domain ?

Thanks, Michael

**Comment by danielweck** [comment]
EPUB.js:
https://s3.amazonaws.com/epubjs-manifest/examples/manifest.html?href=https://readium2.herokuapp.com/pub/L2FwcC9taXNjL2VwdWJzL2NoaWxkcmVucy1saXRlcmF0dXJlLmVwdWI%3D/manifest.json

Hadrien's webpub viewer:
https://hadriengardeur.github.io/webpub-manifest/examples/viewer/?manifest=true&href=https://readium2.herokuapp.com/pub/L2FwcC9taXNjL2VwdWJzL2NoaWxkcmVucy1saXRlcmF0dXJlLmVwdWI=/manifest.json

**Comment by danielweck** [comment]
Make sure to clear your browser caches, and launch an "incognito" window to ensure no caches are used.

**Comment by barbender** [comment]
I have tried the links, but could not find any way to access media overlay
there. They do not seem to support it yet.

Note that CORS problem that I am having is only related to access to
the Spine Item's MO data. (And yes I tried in Incognito mode with cleared cache). Here is what we are seeing in Network tab of dev tools when attempting to access Spine Item's Media Overlay data:

Request URL:http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay?resource=OEBPS%2FText%2Fp001.xhtml
Request Method:GET
Status Code:301 Moved Permanently
Remote Address:[::1]:3000
Referrer Policy:no-referrer-when-downgrade

Response Headers
view source
Connection:keep-alive
Content-Length:161
Content-Type:text/plain; charset=utf-8
Date:Tue, 13 Jun 2017 16:46:24 GMT
Location:/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/media-overlay/?resource=OEBPS%2FText%2Fp001.xhtml
Vary:Accept
X-Powered-By:Express

Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,ru-RU;q=0.8,ru;q=0.6,en;q=0.4
Cache-Control:no-cache
Connection:keep-alive
Host:localhost:3000
Origin:http://localhost:8080
Pragma:no-cache
Referer:http://localhost:8080/dev/index_RequireJS_no-optimize_LITE.html?epub=http://localhost:3000/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJwbVNoZWtzcGlyZS5lcHVi/manifest.json
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Query String Parameters
view source
view URL encoded
resource:OEBPS/Text/p001.xhtml

Do you see anything wrong in the way MO is accessed?
thanks, Michael

**Comment by danielweck** [comment]
HTTP Status Code:301 Moved Permanently

...this doesn't make sense.
In my tests, MO support is working fine when I query the per-spine-item URL, as well as the full aggregated MO.

**Comment by barbender** [comment]
Are you testing this cross-domain? The problem only happens when the request for MO is done cross-domain (in my case from localhost:8080 to localhost:3000).

**Comment by danielweck** [comment]
So, using the "Tales From Shakespeare" EPUB3 Media Overlays ( https://www.readbeyond.it/ebooks/08722688.html ):

https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D/manifest.json/show

https://readium2.herokuapp.com/pub/aHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D/media-overlay/?show=OEBPS%2FText%2Fp001.xhtml

...I compiled and deployed the Evident Point fork of `readium-js` https://github.com/evidentpoint/readium-js/commits/feature/readium2 (original: https://github.com/readium/readium-js/commits/feature/readium2 ):

http://readium-2.surge.sh/?epub=https%3A%2F%2Freadium2.herokuapp.com%2Fpub%2FaHR0cHM6Ly93d3cucmVhZGJleW9uZC5pdC9zYW1wbGVzLzA4NzIyNjg4LmVwdWI%3D%2Fmanifest.json

PS: note that I pushed the merged source tree here: https://github.com/readium/readium-js/commits/feature/readium2-evidentpoint (but eventually I will destroy this branch, this is just to double-check that everything is in sync).

...I observe the following error messages in Chrome:

`smil_webpub_parser.js`
GET `http://readium-2.surge.sh/media-overlay?resource=OEBPS%2FText%2Fp001.xhtml` 404 (Not Found)

...which is indeed correct. There is some error in the code when resolving absolute URLs. Investigating...

**Comment by danielweck** [comment]
I found the "bug". There is a HTTP 301 redirect from `media-overlay?resource=PATH_TO_SPINE_ITEM.xhtml` to `media-overlay/?resource=PATH_TO_SPINE_ITEM.xhtml` (note the extra slash after `media-overlay`), and the CORS headers are not present in the response.

**Comment by danielweck** [comment]
Update: `r2-streamer-js` fix for slash suffix added by HTTP redirect 301 in Media Overlays route (now: `media-overlay.json?resource=chapter.html`)
https://github.com/edrlab/r2-streamer-js/commit/de8e6a434819d7479734266b2ffbce2b6585908e

**Comment by danielweck** [comment]
@barbender please note the changes I made to your code (via a separate branch) to avoid using the `fetch()` API and continue using the standard ReadiumJS "fetchers". Also note the Promise changes (nothing major, you decide how you want it :) ).
https://github.com/readium/readium-js/commit/d63a4c3a9cad08015e96b25afedbc63b91b4682e
