### ISSUE TITLE
Paginated reflow documents: odd column numbers require last empty page handling (for correct scroll spread index)

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-streamer-js#9]

**Comment by danielweck** [comment]
Test with "accessible EPU3" "chapter 4 conclusion"

**Comment by danielweck** [comment]
No fix, IMO.
The minor inconsistency does not break navigation features, and any addition of virtual space after the last odd column index (1-based) would result in pagination re-pass (possibly messing up other complex interactions)

**Comment by JayPanoz** [comment]
cc’ing @HadrienGardeur and @camill-a since we’ve been discussing this issue for weeks as soon as we tested pagination. 

Did some research back then to list possible options but it was difficult to list pros and cons in the absence of others implementations.

Do you want me to list those options there so that we at least can have some written record, or should I open an issue on the Readium CSS repo? 

I guess this would eventually be added to Readium CSS documentation anyways, as implementers will undoubtedly face this issue. So it makes sense to discuss this in the Readium CSS issues.
